server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://manusqldatabase.database.windows.net:1433;database=studentmanagementsystem;encrypt=true;trustServerCertificate=true
    username: manu
    password: 1@Werugha
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
  batch:
    jdbc:
      initialize-schema: always
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 900000  # 1 hour in milliseconds
    refresh-expiration-time: 7200000

